### ISSUE TITLE
issue with setup.py

### ISSUE THREAD

**Issue by rookiepythonat** [IBM/pyxcli#14]
creating 'dist/pyxcli-1.1.7-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyxcli-1.1.7-py2.7.egg
Removing /usr/lib/python2.7/site-packages/pyxcli-1.1.7-py2.7.egg
Copying pyxcli-1.1.7-py2.7.egg to /usr/lib/python2.7/site-packages
pyxcli 1.1.7 is already the active version in easy-install.pth

Installed /usr/lib/python2.7/site-packages/pyxcli-1.1.7-py2.7.egg

folks I am trying to install this and facing below errors.
Appreciate if some one can help me or put me in right direction

Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by tzurE** [comment]
Hi,
What exactly are you trying to run?
is it 
`python setup.py bdist_egg` ?

**Comment by rookiepythonat** [comment]
I ran python setup.py install

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyxcli.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyxcli.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyxcli.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyxcli.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyxcli.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/pyxcli-1.1.7-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyxcli-1.1.7-py2.7.egg
Removing /usr/lib/python2.7/site-packages/pyxcli-1.1.7-py2.7.egg
Copying pyxcli-1.1.7-py2.7.egg to /usr/lib/python2.7/site-packages
pyxcli 1.1.7 is already the active version in easy-install.pth

**Installed /usr/lib/python2.7/site-packages/pyxcli-1.1.7-py2.7.egg**
**Traceback (most recent call last):**
  File "setup.py", line 51, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by rookiepythonat** [comment]
After installing bunch module. It is working .

closing the issue now
